runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: app/static

- url: /.*
  script: auto

- url: /templates
  static_dir: app/templates
